name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    paths:
      - 'package.json'
      - 'src/**'
      - 'public/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Set Git identity to your account
        run: |
          git config --global user.email "rsk.rook@gmail.com"
          git config --global user.name "hroac"

      - name: Build the project
        env:
          REACT_APP_GH_KEY: ${{ secrets.REACT_APP_GH_KEY }}
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npx gh-pages -d build
